---

name: Build RPM
description: Use git-rpm-tools to build self as RPM and SRPM
runs:
  using: "composite"
  steps:
    - name: Switch to branch to leave detached head state
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git checkout -b gha-build
      shell: bash

    - name: Build RPMs and SRPMs
      run: ./scripts/git-rpm-tools -v -x ba
      shell: bash
