---

name: Build Self as RPM
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-rpm:
    name: EL${{ matrix.el_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        el_version: [8, 9, 10]
    container:
      image: almalinux:${{ matrix.el_version }}
    steps:

      - name: Install dependencies
        run: |
          dnf -y install rpmdevtools git

      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Build RPMs
        run: ./scripts/git-rpm-tools
