---

name: Build rpms with self
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-rpm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        el_version: [8, 9, 10]
    container:
      image: almalinux:${{ matrix.el_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          dnf -y install rpmdevtools git

      - name: Build RPMs
        run: ./scripts/git-rpm-tools
